[package]
name = "vfp"
version = "0.1.0"
edition = "2021"
description = "Just a very fast protocol in development"
license = "MIT"
license-file = "LICENSE"
documentation = "https://docs.rs/vfp"
repository = "https://github.com/neodyland/vfp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
clap = { version = "4.1.6", features = ["derive"] }
ed25519 = "2.1.0"
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["full"] }
tokio-stream = "0.1.12"
tokio-util = { version = "0.7.7", features = ["full"] }
uuid = { version = "1.3.0", features = ["v4", "serde"] }